---
- name: Install and configure web service
  hosts:
    - serverc.lab.example.com
    - serverd.lab.example.com

  tasks:
    - name: Install apache
      yum:
        name: apache2
        state: latest

    - name: Enable and start apache
      service:
        name: apache2
        enabled: true
        state: started
  
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest

    - name: Enable and start the firewall
      service:
        name: firewalld
        enabled: true
        state: started
        
  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
